#### COLOUR (macOS Terminal "Clear Dark")

# default statusbar colors (overridden by statusline.conf; kept consistent)
set-option -g status-style bg=default,fg=#E0E0E0

# default window title colors
set-window-option -g window-status-style fg=#465C6D,bg=default

# active window title colors
set-window-option -g window-status-current-style fg=#67B5ED,bg=default,bright

# pane border
set-option -g pane-border-style fg=#35424C
set-option -g pane-active-border-style fg=#6D96B4

# message text
set-option -g message-style bg=#6D96B4,fg=#191D27

# pane number display  (prefix + q)  -- not overridden, takes effect
set-option -g display-panes-active-colour "#67B5ED"
set-option -g display-panes-colour "#465C6D"

# clock  (prefix + t)  -- not overridden, takes effect
set-window-option -g clock-mode-colour "#6CAA71"
